---
- name: ensure nginx user exsist
  ansible.builtin.user:
    name: "{{ nginx_settings__conf_user }}"

- name: settings ./nginx/nginx.conf
  template:
    src: nginx_settings__conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  when: nginx_settings__conf
  notify: restart nginx

- name: settings /conf.d/
  template:
    src: "{{ nginx_settings__vhost_template }}"
    dest: "/etc/nginx/conf.d/{{ nginx_settings__vhost_server_name }}.conf"
    owner: root
    group: root
    mode: 0644
  when: nginx_settings__vhost
  notify: restart nginx

- name: remove default nginx vhost config file (if configured).
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  when: nginx_settings__vhost_remove_default_conf
  notify: restart nginx