---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ nginx_install__dependencies_redhat }}"
    state: present    

- name: add epel repo for redhat
  block:
    - name: import epel gpg key
      ansible.builtin.rpm_key:
        key: "{{ nginx_install__redhat_epel_repo_gpg_key_url }}"
        state: present

    - name: add repository
      ansible.builtin.yum:
        name: "{{ nginx_install__redhat_epel_repo_url }}"
        state: present
  when: nginx_install__redhat_epel_repo

- name: add nginx repo for redhat
  block:
    - name: import nginx gpg key
      ansible.builtin.rpm_key:
        key: "{{ nginx_install__redhat_nginx_repo_gpg_key_url }}"
        state: present

    - name: add nginx repository
      ansible.builtin.yum_repository:
        name: nginx_install__redhat_epel_repo_url
        description: nginx YUM repo
        baseurl: "{{ nginx_install__redhat_nginx_repo_url }}"
        gpgcheck: yes
  when: nginx_install__redhat_nginx_repo

- name: install nginx packages.
  ansible.builtin.package:
    name: "{{ nginx_install__list }}"
    state: present
    update_cache: true
  ignore_errors: yes

- name: ensure nginx is started
  ansible.builtin.service:
    name: nginx
    state: started