---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ nginx_const[ansible_os_family]['dependencies'] }}"
    state: present
    update_cache: true

- name: add nginx repo
  block:
    - name: add gpg key
      ansible.builtin.apt_key:
        url: "{{ nginx_const[ansible_os_family]['nginx_gpg'] }}"
        state: present

    - name: add nginx repo
      ansible.builtin.apt_repository:
        repo: "{{ nginx_const[ansible_os_family]['nginx_repo'] }}"
        state: present
  when: nginx.repo == "nginx"

- name: install nginx packages.
  ansible.builtin.apt:
    name: "{{ nginx_const[ansible_os_family]['packages'] }}"
    state: present
    update_cache: true
  ignore_errors: true