---
- name: ensure nginx user exsist
  ansible.builtin.user:
    name: "{{ nginx_conf.data.user }}"

- name: copy template to remote node
  ansible.builtin.template:
    src: "{{ nginx_conf.src }}"
    dest: "/etc/nginx/{{ nginx_conf.file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ nginx_conf.backup }}"
  notify: restart nginx