---
- name: merge dictionaries
  block:
  - name: register default vars
    include_vars:   
      dir: "{{ role_path }}/defaults/"
      name: nginx_default_vars    

  - name: merge default and new dictionaries 
    set_fact:
      "{{ item.key }}": "{{ nginx_default_vars[item.key] | combine(nginx_merge[item.key], recursive=True)}}"
    with_dict: "{{ nginx_merge }}"
  when: nginx_merge is defined

- name: include nginx install
  include_tasks: ./tasks/install/nginx_install__{{ ansible_os_family | lower }}.yml
  when: nginx_install.enabled

- name: include nginx config
  include_tasks: ./tasks/config/nginx_conf.yml
  when: nginx_conf.enabled

- name: include nginx config
  include_tasks: ./tasks/config/nginx_virtualhost.yml
  when: nginx_virtualhost.enabled

- name: reset dictionaries to default
  set_fact:
    "{{ item.key }}": "{{ update_vars[item.key] | combine( item.value, recursive=True) }}"
  with_dict: "{{ update_vars }}"
  when: merge_dictionaries is defined