---
- name: merge dictionaries
  block:
  - include_vars: 
      file: ../../darexsu.nginx/defaults/main.yml  
      name: nginx_default_vars
  
  - name: merge default and new dictionaries 
    set_fact:
      "{{ item.key }}": "{{ nginx_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
    when: nginx_default_vars[item.key] is defined
    with_dict: "{{ merge }}"

  - name: combine defaults vars with merge dictionary
    set_fact:
      merge: "{{ nginx_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: nginx role is disabled
  meta: end_play
  when: not nginx.enabled

- name: include nginx install
  include_tasks: ./tasks/install/nginx_install__{{ ansible_os_family | lower }}.yml
  when: nginx_install.enabled

- name: include nginx config
  include_tasks: ./tasks/config/nginx_conf.yml
  when: nginx_conf.enabled

- name: include nginx config
  include_tasks: ./tasks/config/nginx_virtualhost.yml
  when: nginx_virtualhost.enabled

- name: reset dictionaries to default
  set_fact:
    "{{ item.key }}": "{{ update_vars[item.key] | combine( item.value, recursive=True) }}"
  with_dict: "{{ update_vars }}"
  when: merge_dictionaries is defined