---
- name: merge dictionaries
  block:
    - include_vars:
        file: ../../darexsu.nginx/defaults/main.yml
        name: nginx_default_vars

    - name: merge default and new dictionaries
      set_fact:
        "{{ item.key }}": "{{ nginx_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
      when: nginx_default_vars[item.key] is defined
      with_dict: "{{ merge }}"

    - name: combine defaults vars with merge dictionary
      set_fact:
        merge: "{{ nginx_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: nginx role is disabled
  meta: end_play
  when: not nginx.enabled

- name: "-> 01_Nginx_install_{{ ansible_os_family }}.yml"
  include_tasks: "./tasks/01_Nginx_install_{{ ansible_os_family }}.yml"
  when: nginx_install.enabled

- name: service facts
  ansible.builtin.service_facts:

- name: "-> 02_Nginx_config_nginx_conf.yml"
  include_tasks: "./tasks/02_Nginx_config_nginx_conf.yml"
  when: nginx_conf.enabled and ansible_facts.services is search("nginx")

- name: "-> 03_Nginx_config_virtualhost.yml"
  include_tasks: "./tasks/03_Nginx_config_virtualhost.yml"
  when: nginx_virtualhost[item.key]['enabled'] and ansible_facts.services is search("nginx")
  with_dict: "{{ nginx_virtualhost }}"

- name: "ensure nginx is {{ nginx['service']['state'] }}"
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx['service']['state'] }}"
    enabled: "{{ nginx['service']['enabled'] }}"
  when: ansible_facts.services is search("nginx")