---
- name: include nginx install
  include_tasks: ./tasks/install/nginx_install__{{ ansible_os_family | lower }}.yml
  when: nginx_install

- name: include nginx config
  include_tasks: ./tasks/config/nginx_config.yml
  when: nginx_config