---
- name: ensure nginx user exsist
  ansible.builtin.user:
    name: "{{ nginx_conf.vars.user }}"

- name: copy template to remote node
  ansible.builtin.template:
    src: nginx_conf.j2
    dest: "/etc/nginx/{{ nginx_conf.file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx