---
- name: ensure nginx user exsist
  ansible.builtin.user:
    name: "{{ nginx_config__conf_user }}"

- name: config ./nginx/nginx.conf
  ansible.builtin.template:
    src: nginx_config__conf.j2
    dest: "{{ nginx_config__conf_file }}"
    owner: root
    group: root
    mode: 0644
  when: nginx_config__conf
  notify: restart nginx

- name: config /conf.d/
  ansible.builtin.template:
    src: "{{ nginx_config__vhost_template }}"
    dest: "{{ nginx_config__vhost_file }}"
    owner: root
    group: root
    mode: 0644
  when: nginx_config__vhost
  notify: restart nginx
