---
- name: Converge
  hosts: all
 
  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
  
  roles:
    - role: darexsu.nginx
      # install
      nginx_install: true
      
      # config 
      nginx_config: true
      # config -> nginx.conf
      nginx_config__conf: true
      # config -> virtualhost
      nginx_config__vhost: true
      
      # actions
      nginx_actions: true   
