---
- name: Converge
  hosts: all

  roles:
    - role: darexsu.nginx
      # install
      nginx_install: true
      
      # config 
      nginx_config: true
      # config -> nginx.conf
      nginx_config__conf: true
      # config -> virtualhost
      nginx_config__vhost: true
      
      # actions
      nginx_actions: true   
