---
- name: Converge
  hosts: all  
 
  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
  
  tasks:
  - name: 1 start role darexsu.nginx
    include_role: 
      name: darexsu.nginx
    vars:
      merge_dictionaries:
        # Install -> packages
        nginx_install:
          enabled: true
          packages: [nginx]
        # Install -> repository
        nginx_repo:  
          epel:
            enabled: true
          nginx:
            enabled: true
        # Config -> nginx.conf
        nginx_conf:
          enabled: true
          vars:
            user: "www-data"
            worker_processes: "auto"
            error_log: "/var/log/nginx/error.log notice"
            pidfile: "/var/run/nginx.pid"
            worker_connections: "1024"
        # Config -> {virtualhost}.conf
        nginx_virtualhost: 
          enabled: true
          file: [virtualhost.conf]
          vars:
            listen_port: "80"
            listen_ipv6: false
            server_name: "localhost"
            root: "/usr/share/nginx/html"
            index: "index.html index.htm index.php"
            error_page: ""
            access_log: false
            error_log: false
            php_fpm:
              tcp_ip_socket:
                listen: "127.0.0.1:9000"

  - name: 2 remove default.conf
    include_role: 
      name: darexsu.nginx
    vars:
      merge_dictionaries:
        # Config -> {virtualhost}.conf
        nginx_virtualhost: 
          enabled: true
          file: ["default.conf"]
          state: "absent"