---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:    
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             Nginx 
      nginx:
        enabled: true
        src: "distribution"
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             install packages
      nginx_install:
        enabled: true
        packages: [nginx]
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             nginx.conf
      nginx_conf:
        enabled: true
        vars:
          user: "www-data"
          worker_processes: "auto"
          error_log: "/var/log/nginx/error.log notice"
          pidfile: "/var/run/nginx.pid"
          worker_connections: "1024"
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄             virtualhost
      nginx_virtualhost:
      # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄             delete first config
        default_conf:
          enabled: true
          file: "default.conf"
          state: "absent"
      # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄             add second config
        new_conf:
          enabled: true
          file: "new.conf"
          state: "present"
          src: "nginx__virtualhost.j2"
          backup: false
          vars:
            listen_port: "80"
            listen_ipv6: false
            server_name: "localhost"
            root: "/usr/share/nginx/html"
            index: "index.html index.htm index.php"
            error_page: ""
            access_log: false
            error_log: false
            fastcgi_pass: "127.0.0.1:9000"
    
    # ┌┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄              Apache stop and disable on boot
      apache:
        enabled: true  
        service:
          enabled: false
          state: "stopped"

  tasks:
  - name: role darexsu nginx
    include_role: 
      name: darexsu.nginx
